<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HP-PC" failures="1" tests="2" name="neOStoxTest.ValidateUserNameAndFundsusingProperty" time="28.807" errors="0" timestamp="2022-12-06T14:34:13 IST" skipped="0">
  <testcase classname="neOStoxTest.ValidateUserNameAndFundsusingProperty" name="getFunds" time="16.293"/>
  <system-out>
    <![CDATA[waiting for 1000 millis
waiting for 1000 millis
funds are Rs.5,00,000.00
tc is passed]]>
  </system-out>
  <testcase classname="neOStoxTest.ValidateUserNameAndFundsusingProperty" name="validateUserName" time="12.514">
    <failure message="TC failed actual not equal expected expected [Hi Rushikesh Pagar1] but found [Hi Rushikesh Pagar]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: TC failed actual not equal expected expected [Hi Rushikesh Pagar1] but found [Hi Rushikesh Pagar]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at neOStoxTest.ValidateUserNameAndFundsusingProperty.validateUserName(ValidateUserNameAndFundsusingProperty.java:69)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateUserName -->
  <system-out>
    <![CDATA[waiting for 1000 millis
actual username is Hi Rushikesh Pagar
taking value from property Hi Rushikesh Pagar1
testcase validateUserNameis failed
taking screenshot]]>
  </system-out>
</testsuite> <!-- neOStoxTest.ValidateUserNameAndFundsusingProperty -->
